name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Executa o workflow quando algo é enviado para a branch "main".

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use a versão do Node compatível com o seu projeto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Substitua pelo comando de build do seu projeto

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod
